# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  ci-commons-demo-scan:
    permissions:
      id-token: write # This is required for requesting the JWT
      actions: read
      contents: read  # -> Required by actions/checkout@v3 if checking out a private repository
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Endor Labs Scan Pull Request
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@main
        with:
          namespace ${{ secrets.ENDOR_NAMESPACE }}:
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          enable_github_action_token: "false"
          scan_summary_output_type: "table"
          ci_run: "true"
          sarif_file: endor-findings.sarif
      - name: Endor Labs Scan Push to main
        if: github.event_name == 'push'
        uses: endorlabs/github-action@main
        with:
          namespace: ${{ secrets.ENDOR_NAMESPACE }}
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          enable_github_action_token: "false"
          scan_summary_output_type: "table"
          ci_run: "false"
          sarif_file: endor-findings.sarif

      - name: Upload findings to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: endor-findings.sarif
      - name: Get endorctl binary
        shell: bash
        run: ./.github/scripts/download-endorctl.sh
      - name: Generate SBOM
        run: endorctl export-sbom --package-version-name "mvn://com.visualpathit:vprofile@v2" --api-key ${{ secrets.ENDOR_API_CREDENTIALS_KEY }} --api-secret ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }} --namespace ${{ secrets.ENDOR_NAMESPACE }} > sbom.cdx.json
      - name: Save SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom.cdx.json
          path: sbom.cdx.json
      - name: Generate VEX
        run: endorctl export-vex --verbose --package-version-name "mvn://com.visualpathit:vprofile@v2" --api-key ${{ secrets.ENDOR_API_CREDENTIALS_KEY }} --api-secret ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }} --namespace ${{ secrets.ENDOR_NAMESPACE }} > vex.cdx.json
      - name: Save VEX artifact
        uses: actions/upload-artifact@v3
        with:
          name: vex.cdx.json
          path: vex.cdx.json
